ワークフロー整理

diff --git a/.github/workflows/image-release.yml b/.github/workflows/image-release.yml
--- a/.github/workflows/image-release.yml
+++ b/.github/workflows/image-release.yml
@@ -1,30 +1,105 @@
-# This is a basic workflow that is manually triggered
+# テストにパスしたDockerImageに、正式なバージョンを付与する
 
-name: Kit Docker Image Release
+name: Release Kit Image
 
-# Controls when the action will run. Workflow runs when manually triggered using the UI
-# or API.
+# トリガーイベントの指定
 on:
+  # ブラウザ上からの手動実行設定
   workflow_dispatch:
-    # Inputs the workflow accepts.
     inputs:
-      name:
-        # Friendly description to be shown in the UI instead of 'name'
-        description: 'Person to greet'
-        # Default value if no value is explicitly provided
-        default: 'World'
-        # Input has to be provided for the workflow to run
+      # テスト実施バージョンの指定
+      test_version:
+        description: 'テスト実施バージョン (Format: test.N  ※Nは整数)'
+        default: test.N
+        required: true
+      # リリースバージョンの指定
+      release_version:
+        description: '付与するリリースバージョン (Format: 4.N.n  ※N,nは整数)'
+        default: 4.N.n
+        required: true
+      # latestバージョンを付与するかの指定(yesで付与)
+      append_latest_enable:
+        description: 'latestバージョンの付与 (yes/no)'
+        default: 'yes'
+        required: true
+      # バージョン形式のチェック有無
+      check_format_enable:
+        description: '入力値のFormatチェックの実施 (yes/no)'
+        default: 'yes'
         required: true
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs:
-  # This workflow contains a single job called "greet"
-  greet:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+# 環境変数の設定
+env:
+  RESISTRY_URL: ghcr.io/${{ github.repository_owner }}
+  IMAGE_NAME: burger-war-kit
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
+# 実行する処理
+jobs:
+  image-release:
+    runs-on: ubuntu-20.04
+
     steps:
-    # Runs a single command using the runners shell
-    - name: Send greeting
-      run: echo "Hello ${{ github.event.inputs.name }}"
+    # 入力値からバージョン情報取得
+    - name: Set Version When Not Manual
+      if: github.event_name == 'workflow_dispatch'
+      run: |
+        echo "TEST_VERSION=${{ github.event.inputs.test_version }}" >> ${GITHUB_ENV}
+        echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> ${GITHUB_ENV}
+
+    # バージョン情報出力
+    - name: Print Version
+      run: |
+        echo "TEST_VERSION: ${TEST_VERSION}"
+        echo "RELEASE_VERSION: ${RELEASE_VERSION}"
+        echo "Append latest: ${{ github.event.inputs.append_latest_enable }}"
+        echo "Check format: ${{ github.event.inputs.check_format_enable }}"
+  
+    # テストバージョンのフォーマットチェック
+    - name: Check Input Test Version
+      if: github.event.inputs.check_format_enable == 'yes'
+      run: |
+        if echo "${TEST_VERSION}" | grep -E "^test\.[1-9][0-9]*$"; then
+          echo "Valid test version"
+        else
+          echo "Invalid test version"
+          exit 1
+        fi
+
+    # Releaseバージョンのフォーマットチェック
+    - name: Check Input Release Version
+      if: github.event.inputs.check_format_enable == 'yes'
+      run: |
+        if echo "${RELEASE_VERSION}" | grep -E "^4\.[0-9]+\.[0-9]+$"; then
+          echo "Valid release version"
+        else
+          echo "Invalid release version"
+          exit 1
+        fi
+
+    # ghcr.ioにログイン
+    - name: Login to ghcr.io
+      uses: docker/login-action@v1
+      with:
+        registry: ghcr.io
+        username: ${{ secrets.GHCR_USERNAME }}
+        password: ${{ secrets.GHCR_PASSWORD }}
+
+    # テストバージョンの取得
+    - name: Pull Test Version Image
+      run: |
+        docker pull ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:${TEST_VERSION}
+
+    # テストバージョンのイメージに正式バージョンを付与
+    - name: Push Official Image Version
+      run: |
+        docker tag ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:${TEST_VERSION} \
+                   ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:${RELEASE_VERSION}
+        docker push ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:${RELEASE_VERSION}
+
+    # テストバージョンのイメージにlatestバージョンを付与
+    - name: Push Official Image Version
+      if: github.event.inputs.append_latest_enable == 'yes'
+      run: |
+        docker tag ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:${TEST_VERSION} \
+                   ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
+        docker push ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
